---
output:
  pdf_document: default
  html_document: default
---
```{r results = FALSE, message = FALSE, warning = FALSE}
source("weaving-space-utils.R")
source("biaxial-weave-units.R")
source("triaxial-weave-units.R")
source("weave-map.R")

library(sf)        # vector spatial data
library(tmap)      # thematic maps
library(dplyr)     # data wrangling
```

# Plain weave with gaps

```{r}
m <- make_twill_matrix(1) %>%
  repmat(2) %>%
  augment_with_values(2, 0)
unit <- get_biaxial_weave_unit(type = "this", tie_up = m, strands = "abcd--|efgh--")
unit$primitive %>% plot(border = NA)
```

# 2 x 2 basket weave with gaps

```{r}
m <- make_basket_matrix(2) %>% 
  augment_with_values(2, 0)
unit <- get_biaxial_weave_unit(type = "this", tie_up = m, strands = "abcd--|efgh--")
unit$primitive %>% plot(border = NA)
```

# 6 x 6 basket weave
Note that the missing threads mean we don't need rows and columns of 0s added to the matrix

```{r}
m <- make_basket_matrix(6)
unit <- get_biaxial_weave_unit(type = "this", tie_up = m, strands = "abcd--|efgh--")
unit$primitive %>% plot(border = NA)
```
